using Content.Client._DEN.CartridgeLoader.Cartridges.Widgets;
using Content.Shared._DEN.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly Dictionary<Guid, NanoChatConversation> _conversations = new();
    private readonly Dictionary<Guid, NanoChatMessageEntry> _messageIdToUi = new();

    private ISawmill _sawmill;

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("nanochat.ui");
    }

    public void UpdateState(NanoChatUiState state)
    {

    }
}
