using Content.Client._DEN.CartridgeLoader.Cartridges.Widgets;
using Content.Shared._DEN.CartridgeLoader.Cartridges;
using Content.Shared._DEN.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private Dictionary<Guid, NanoChatConversation> _conversations = new();
    private Dictionary<Guid, NanoChatMessage> _messages = new();
    private Dictionary<uint, NanoChatUser> _users = new();
    private Dictionary<Guid, NanoChatMessageEntry> _messageIdToUi = new();
    private ISawmill _sawmill;

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("nanochat.ui");
    }

    public void UpdateState(NanoChatUiState state)
    {
        _conversations = state.Conversations;
        _messages = state.Messages;
        _users = state.RelevantUsers;

        ChatsContainer.SetConversations(state.Conversations, state.CurrentConversationId);
    }

    private void AddMessageEntry(Guid messageId, NanoChatMessageEntry messageEntry)
    {
        _messageIdToUi.Add(messageId, messageEntry);
    }
}
