- type: language
  abstract: true
  id: BaseAudible
  name: language-base-audible
  components:
  - type: SpeechTransformable
  - type: RadioTransmittable
  - type: Audible
  - type: WhisperMuffle
    muffle: true
