- type: language
  id: Default
  name: language-default
  displayInChat: false
  components:
  - type: SpeechTransformable
  - type: RadioTransmittable
  - type: Audible
  - type: WhisperMuffle
    muffle: true
