using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CreateCategoryPopup : FancyWindow
{
    public event Action<CategoryCreationRequest>? OnSubmit;

    public CreateCategoryPopup()
    {
        RobustXamlLoader.Load(this);

        ButtonSubmit.OnPressed += _ => OnSubmitPressed();
    }

    private void OnSubmitPressed()
    {
        var request = new CategoryCreationRequest
        {
            CategoryName = CategoryNameEdit.Text,
            CategoryColor = CategoryColorPicker.Color
        };

        OnSubmit?.Invoke(request);
    }
}

public record struct CategoryCreationRequest
{
    public string CategoryName { get; set; }
    public Color CategoryColor { get; set; }
}
