using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class DenCategoryContainer : PanelContainer
{
    private bool _isExpanded;

    public DenCategoryContainer()
    {
        RobustXamlLoader.Load(this);

        HeaderButton.OnPressed += _ => ToggleExpanded();
        UpdateExpandedState();
    }

    private void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        LoadoutContainer.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }
}
