using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class DenLoadoutButtons : ContainerButton
{
    public string Text { get; set; } = "Loadout";

    public DenLoadoutButtons()
    {
        RobustXamlLoader.Load(this);


    }
}
