using System.Linq;
using Content.Shared._DEN.Loadout;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class DenLoadoutTab : ContainerButton
{
    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private CreateCategoryPopup? _createCategoryPopup;
    private CreateLoadoutPopup? _createLoadoutPopup;
    private HumanoidCharacterProfile? _profile;

    private List<(Guid CategoryId, string CategoryName)> _categories;

    public DenLoadoutTab()
    {
        RobustXamlLoader.Load(this);

        _categories = new();
        RefreshCategories();

        ButtonCreateCategory.OnPressed += _ => OnTryCreateCategory();
        ButtonCreateLoadout.OnPressed += _ => OnTryCreateLoadout();
    }

    public void RefreshCategories()
    {
        _categories.Clear();

        if (_profile?.LoadoutCategories == null)
            return;

        foreach (var (categoryId, category) in _profile.LoadoutCategories)
        {
            _categories.Add((categoryId, category.Name));
        }
    }

    public void SetProfile(HumanoidCharacterProfile? newProfile)
    {
        _profile = newProfile;
    }

    private void OnTryCreateCategory()
    {
        if (_createCategoryPopup != null)
            return;

        _createCategoryPopup = new CreateCategoryPopup();
        _createCategoryPopup.OnSubmit += OnSubmitNewCategory;
        _createCategoryPopup.OnClose += OnClose;
        _createCategoryPopup.OpenCentered();
    }

    private void OnSubmitNewCategory(CategoryCreationRequest request)
    {
        var guid = Guid.NewGuid();
        var category = new DenLoadoutCategory
        {
            Id = guid,
            Color = request.CategoryColor.ToHex(),
            Name = request.CategoryName,
            Priority = GetNextCategoryPriority()
        };

        _profile = _profile?.WithLoadoutCategory(guid, category);
        OnPreferenceUpdated?.Invoke(_profile);

        RefreshCategories();
        OnClose();
    }

    private void OnTryCreateLoadout()
    {
        if (_createLoadoutPopup != null)
            return;

        _createLoadoutPopup = new CreateLoadoutPopup(_categories);
        _createLoadoutPopup.OnSubmit += OnSubmitNewLoadout;
        _createLoadoutPopup.OnClose += OnClose;
        _createLoadoutPopup.OpenCentered();
    }

    private void OnSubmitNewLoadout(LoadoutCreationRequest request)
    {
        var guid = Guid.NewGuid();
        var loadout = new DenLoadout
        {
            Id = guid,
            Name = request.LoadoutName,
            LoadoutCategory = request.CategoryId,
            Priority = GetNextLoadoutPriority(request.CategoryId)
        };

        _profile = _profile?.WithNewLoadout(guid, request.CategoryId, loadout);
        OnPreferenceUpdated?.Invoke(_profile);

        RefreshCategories();
        OnClose();
    }

    private int GetNextCategoryPriority()
    {
        if (_profile == null)
            return 0;

        var loadoutCategoryCount = _profile.LoadoutCategories.Count;
        return loadoutCategoryCount + 1;
    }

    private int GetNextLoadoutPriority(Guid categoryId)
    {
        if (_profile == null)
            return 0;

        var category = _profile.LoadoutCategories.Values.FirstOrNull(c => c.Id == categoryId);

        if (category == null)
            return 0;

        var memberCount = category.Value.Members.Count;
        return memberCount + 1;
    }

    private void OnClose()
    {
        _createCategoryPopup?.Orphan();
        _createCategoryPopup = null;
    }
}
