using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.CartridgeLoader.Cartridges.Widgets;

[GenerateTypedNameReferences]
public sealed partial class NanoChatConversationEntry : BoxContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private const string ConversationTitleColor = "#d9d9d9";
    private ISawmill _sawmill = default!;

    public event Action? OnConversationClicked;

    public NanoChatConversationEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ConversationButton.OnPressed += _ => OnConversationClicked?.Invoke();
        _sawmill = _logManager.GetSawmill("nanochat.ui.entry");
    }

    public void SetConversationTitle(string title)
    {
        TitleLabel.Text = $"[color={ConversationTitleColor}][bold]{title}[/bold][/color]";
    }

    public void SetConversationSubtitle(string subtitle)
    {
        SubtitleLabel.Text = $"[color=white][font size=10]{subtitle}[/font][/color]";
    }

    public void SetPressed(bool pressed)
    {
        ConversationButton.Pressed = pressed;
    }

    public void SetVisible(bool visibility)
    {
        Visible = visibility;
    }
}
