using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.CartridgeLoader.Cartridges.Widgets;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageBox : PanelContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;

    public NanoChatMessageBox()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("nanochat.ui.messagebox");
    }
}
