using Content.Shared._DEN.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.CartridgeLoader.Cartridges.Widgets;

[GenerateTypedNameReferences]
public sealed partial class NanoChatChatsContainer : BoxContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private readonly ISawmill _sawmill;

    public event Action<Guid?>? OnChatClicked;

    public NanoChatChatsContainer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("nanochat.ui.chatscontainer");
    }

    public void SetConversations(Dictionary<Guid, NanoChatConversation> conversations,
        Guid? currentConversationId = null)
    {
        foreach (var pair in conversations)
        {
            BuildConversation(pair.Value, currentConversationId == pair.Key);
        }
    }

    private void BuildConversation(NanoChatConversation conversation, bool pressed)
    {
        var userEntry = new NanoChatConversationEntry();

        userEntry.SetConversationTitle(conversation.Title);
        userEntry.SetConversationSubtitle(conversation.Subtitle);
        userEntry.SetPressed(pressed);

        userEntry.OnConversationClicked += () => OnChatClicked?.Invoke(conversation.Id);
    }
}
