using System.Text;
using Content.Shared._DEN.Requirements.Managers;
using Content.Shared._DEN.Traits.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Lobby.UI.Traits;

[GenerateTypedNameReferences]
public sealed partial class EntityTraitSelector : BoxContainer
{
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IPlayerRequirementManager _requirements = default!;

    public event Action<bool>? PreferenceChanged;

    public int Cost { private set; get; } = 0;
    public bool Preference
    {
        get => SelectorCheckbox.Pressed;
        set => SelectorCheckbox.Pressed = value;
    }

    public ProtoId<EntityTraitPrototype>? PrototypeId { private set; get; } = null;

    private HumanoidCharacterProfile? _profile = null;
    private EntityTraitPrototype _trait = default!;

    public EntityTraitSelector(EntityTraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetTrait(trait);
        SelectorCheckbox.OnToggled += args => { PreferenceChanged?.Invoke(args.Pressed); };
        SelectorCheckbox.TooltipSupplier = SupplyTooltip;
    }

    public void SetProfile(HumanoidCharacterProfile? newProfile)
    {
        _profile = newProfile;
        UpdatePreferenceState();
    }

    private void SetTrait(EntityTraitPrototype trait)
    {
        Cost = trait.Cost;
        PrototypeId = trait.ID;
        _trait = trait;

        var text = "";

        if (trait.Cost != 0)
            text += $"[{trait.Cost}] ";

        text += Loc.GetString(trait.Name);
        SelectorCheckbox.Text = text;
        UpdateVisibility(trait);
    }

    /// <summary>
    ///     Retrieve this session's context.
    /// </summary>
    /// <returns>The local player's session context.</returns>
    private PlayerRequirementContext GetContext()
    {
        var session = _player.LocalSession;
        if (session == null)
            return new();

        var context = _requirements.GetPlayerContext(session);
        return context;
    }

    private void UpdatePreferenceState()
    {
        var traitId = _trait.ID;
        Preference = _profile?.EntityTraitPreferences.Contains(traitId) == true;
    }

    /// <summary>
    ///     Toggles the visibility of this selector, depending on the requirements of a given trait.
    /// </summary>
    /// <param name="trait">The trait to check the requirements of.</param>
    private void UpdateVisibility(EntityTraitPrototype trait)
    {
        var context = GetContext();
        Visible = !SharedPlayerRequirementManager.ShouldHide(context, trait.Requirements);
    }

    /// <summary>
    ///     Provide a tooltip to this control if it has a valid trait set.
    ///     This includes the trait's description and its requirement text.
    /// </summary>
    /// <returns>A tooltip with the trait's description, if this control has a trait.</returns>
    private Tooltip? SupplyTooltip(Control sender)
    {
        if (_trait is null)
            return null;

        var context = _trait.Requirements.Count > 0
            ? GetContext()
            : null;

        var tooltipString = ConstructTooltipDescription(_trait, context);
        if (tooltipString.Length == 0)
            return null;

        var tooltip = new Tooltip();
        if (FormattedMessage.TryFromMarkup(tooltipString, out var msg))
            tooltip.SetMessage(msg);

        return tooltip;
    }

    /// <summary>
    ///     Construct a full tooltip description for a given trait.
    /// </summary>
    /// <param name="trait">The trait to construct a description out of.</param>
    /// <returns>The tooltip text associated with this trait.</returns>
    private static string ConstructTooltipDescription(EntityTraitPrototype trait,
        PlayerRequirementContext? context = null)
    {
        var tooltipBuilder = new StringBuilder();

        // Add description
        if (trait.Description is not null)
            tooltipBuilder.AppendLine(Loc.GetString(trait.Description.Value));

        // Add requirement reason texts
        if (trait.Requirements.Count > 0)
        {
            tooltipBuilder.AppendLine(); // Empty line
            foreach (var requirement in trait.Requirements)
            {
                var reason = requirement.GetReason(context);
                if (reason is null)
                    continue;

                tooltipBuilder.AppendLine(reason);
            }
        }

        var tooltipString = tooltipBuilder.ToString().Trim();
        return tooltipString;
    }

    public void UpdateAppearance(bool invalid)
    {
        if (_trait is null)
            return;

        var passRequirements = PassesRequirements();
        var wouldFail = WouldFailIfSelected();
        SelectorCheckbox.Disabled = (!passRequirements || wouldFail) && !Preference;

        // Change font color if invalid
        Color? fontColor = null;
        if (invalid)
            fontColor = Color.Red;
        else if (!passRequirements || wouldFail)
            fontColor = Color.Gray;

        SelectorCheckbox.Label.FontColorOverride = fontColor;
    }

    /// <summary>
    ///     Gets whether or not this trait would fail requirements if selected.
    /// </summary>
    public bool WouldFailIfSelected()
    {
        // already selected or no trait
        if (Preference || PrototypeId == null)
            return false;

        var selectedProfile = _profile?.WithEntityTraitPreference(PrototypeId.Value, _protoMan);
        return !PassesRequirements(selectedProfile);
    }

    /// <summary>
    ///     Gets whether or not this selector passes trait requirements.
    /// </summary>
    public bool PassesRequirements(HumanoidCharacterProfile? withProfile = null)
    {
        var context = GetContext() with { Profile = withProfile ?? _profile };
        var passRequirements = SharedPlayerRequirementManager.CheckRequirements(context, _trait.Requirements);

        return passRequirements;
    }
}
