using Content.Shared._DEN.Traits.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Traits;

[GenerateTypedNameReferences]
public sealed partial class EntityTraitSelector : BoxContainer
{
    public event Action<bool>? PreferenceChanged;

    public int Cost { private set; get; } = 0;
    public bool Preference
    {
        get => SelectorCheckbox.Pressed;
        set => SelectorCheckbox.Pressed = value;
    }

    public ProtoId<EntityTraitPrototype>? PrototypeId { private set; get; } = null;

    public EntityTraitSelector(EntityTraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        SetTrait(trait);
        SelectorCheckbox.OnToggled += args => { PreferenceChanged?.Invoke(args.Pressed); };
    }

    private void SetTrait(EntityTraitPrototype trait)
    {
        Cost = trait.Cost;
        PrototypeId = trait.ID;

        var text = "";

        if (trait.Cost != 0)
            text += $"[{trait.Cost}] ";

        text += Loc.GetString(trait.Name);
        SelectorCheckbox.Text = text;

        if (trait.Description is not null)
            SelectorCheckbox.ToolTip = Loc.GetString(trait.Description.Value);
    }

    public void SetInvalid(bool invalid)
    {
        SelectorCheckbox.Label.FontColorOverride = invalid ? Color.Red : null;
    }
}
