using System.Linq;
using Content.Client.Lobby.UI;
using Content.Shared._DEN.Traits.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Traits;

[GenerateTypedNameReferences]
public sealed partial class TraitCategoryBox : BoxContainer
{
    private readonly IPrototypeManager _prototypeManager;

    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private HumanoidCharacterProfile? _profile = null;
    private List<EntityTraitSelector> _selectors = new();
    private TraitCategoryPrototype? _category = null;

    public int SelectedTraits => _selectors.Count(s => s.Preference);
    public int TotalCost => _selectors.Where(s => s.Preference).Sum(s => s.Cost);

    public TraitCategoryBox(IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
    }

    public void SetProfile(HumanoidCharacterProfile? newProfile)
    {
        _profile = newProfile;
    }

    public void SetLabel(string text)
    {
        CategoryHeaderLabel.Text = text;
    }

    public void SetTraits(List<EntityTraitPrototype> traits)
    {
        InnerList.RemoveAllChildren();
        _selectors = new();

        foreach (var trait in traits)
        {
            if (!trait.Selectable)
                continue;

            var selector = new EntityTraitSelector(trait);
            selector.SetProfile(_profile);
            selector.PreferenceChanged += p => { OnPreferenceChanged(selector, p); };

            _selectors.Add(selector);
            InnerList.AddChild(selector);
        }

        UpdateCategory();
    }

    public void SetCategory(TraitCategoryPrototype category)
    {
        _category = category;
        UpdateCategory();
    }

    private void UpdateCategory()
    {
        CategoryHeaderLabel.Visible = true;

        if (_category != null)
            SetLabel(Loc.GetString(_category.Name));

        var invalidCategory = false;

        if (_category is { MaxTraitPoints: >= 0 })
        {
            CategoryMaxTraitLabel.Visible = true;
            CategoryMaxTraitLabel.Text = Loc.GetString("humanoid-profile-editor-trait-count-hint",
                ("current", TotalCost),
                ("max", _category.MaxTraitPoints));

            invalidCategory = invalidCategory || TotalCost > _category.MaxTraitPoints;
        }
        else
            CategoryMaxTraitLabel.Visible = false;

        foreach (var selector in _selectors)
        {
            selector.SetProfile(_profile);
            selector.UpdateAppearance(invalidCategory);
        }
    }

    private void OnPreferenceChanged(EntityTraitSelector selector, bool toggled)
    {
        if (selector.PrototypeId is null)
            return;

        // Make sure it doesn't invalidate this trait. Otherwise...
        if (toggled && selector.WouldFailIfSelected())
            return;

        // Get the new profile state.
        if (toggled)
            _profile = _profile?.WithEntityTraitPreference(selector.PrototypeId.Value, _prototypeManager);
        else
            _profile = _profile?.WithoutEntityTraitPreference(selector.PrototypeId.Value, _prototypeManager);

        OnPreferenceUpdated?.Invoke(_profile);
        UpdateCategory();
    }
}
