using System.Linq;
using Content.Client.Lobby.UI;
using Content.Shared._DEN.Traits.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Traits;

[GenerateTypedNameReferences]
public sealed partial class TraitCategoryBox : BoxContainer
{
    private readonly IPrototypeManager _prototypeManager;

    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private HumanoidCharacterProfile? _profile = null;
    private List<EntityTraitSelector> _selectors = new();

    public int SelectedTraits => _selectors.Count(s => s.Preference);
    public int TotalCost => _selectors.Where(s => s.Preference).Sum(s => s.Cost);

    public TraitCategoryBox(IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
    }

    public void SetProfile(HumanoidCharacterProfile? newProfile)
    {
        _profile = newProfile;
    }

    public void SetLabel(string text)
    {
        CategoryHeaderLabel.Text = text;
    }

    public void SetTraits(List<EntityTraitPrototype> traits)
    {
        InnerList.RemoveAllChildren();
        _selectors = new();

        foreach (var trait in traits)
        {
            if (!trait.Selectable || trait.AllowedSpecies is not null
                    && (_profile?.Species is null || !trait.AllowedSpecies.Contains(_profile.Species)))
                continue;

            var selector = new EntityTraitSelector(trait);
            selector.Preference = _profile?.EntityTraitPreferences.Contains(trait.ID) == true;
            selector.PreferenceChanged += p => { OnPreferenceChanged(selector, p); };

            _selectors.Add(selector);
            InnerList.AddChild(selector);
        }
    }

    public void SetCategory(TraitCategoryPrototype category)
    {
        CategoryHeaderLabel.Visible = true;
        CategoryHeaderLabel.Text = Loc.GetString(category.Name);

        if (category is { MaxTraitPoints: >= 0 })
        {
            CategoryMaxTraitLabel.Visible = true;
            CategoryMaxTraitLabel.Text = Loc.GetString("humanoid-profile-editor-trait-count-hint",
                ("current", TotalCost),
                ("max", category.MaxTraitPoints));

            var tooManySelected = TotalCost > category.MaxTraitPoints;
            foreach (var selector in _selectors)
                selector.SetInvalid(tooManySelected);
        }
        else
            CategoryMaxTraitLabel.Visible = false;
    }

    private void OnPreferenceChanged(EntityTraitSelector selector, bool toggled)
    {
        if (selector.PrototypeId is null)
            return;

        if (toggled)
            _profile = _profile?.WithEntityTraitPreference(selector.PrototypeId.Value, _prototypeManager);
        else
            _profile = _profile?.WithoutEntityTraitPreference(selector.PrototypeId.Value, _prototypeManager);

        OnPreferenceUpdated?.Invoke(_profile);
    }
}
