using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Denu.UI.Denu.Components;

[GenerateTypedNameReferences]
public sealed partial class DenuSidebar : BoxContainer
{
    public event Action<int>? OnTabSelected;
    private readonly ButtonGroup _buttonGroup;

    public DenuSidebar()
    {
        RobustXamlLoader.Load(this);
        _buttonGroup = new ButtonGroup();
    }

    public void AddTab(string title, int index)
    {
        var button = new Button
        {
            Text = title,
            ToggleMode = true,
            Group = _buttonGroup,
            TextAlign = Label.AlignMode.Left
        };

        button.OnPressed += _ => OnTabSelected?.Invoke(index);
        AddChild(button);

        if (index == 0)
        {
            button.Pressed = true;
        }
    }

    public void ClearTabs()
    {
        DisposeAllChildren();
    }
}
