using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.UserInterface.Systems.Language.Windows;

[GenerateTypedNameReferences]
public sealed partial class LanguageWindow : FancyWindow
{
    public bool NeedsFullRebuild;

    public LanguageWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
