- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  # Begin DEN: Use PlayerRequirements
  # requirements:
  #   - !type:DepartmentTimeRequirement
  #     department: Engineering
  #     time: 2.5h
  playerRequirements:
  - !type:PlayerDepartmentPlaytimeRequirement
    department: Engineering
    minTime: 2.5h
  # End DEN
  startingGear: StationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: StationEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: StationEngineerChameleonOutfit
  job: StationEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
