using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.ResourceOverview.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._DEN.ResourceOverview.UI;

[GenerateTypedNameReferences]
public sealed partial class ResourceOverviewConsoleWindow : FancyWindow
{
    public ResourceOverviewConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(ResourceOverviewBoundInterfaceState state)
    {

    }
}
