using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.ResourceOverview.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._DEN.ResourceOverview.UI;

[GenerateTypedNameReferences]
public sealed partial class ResourceOverviewEntryButton : BoxContainer
{
    public event Action? OnPressed;

    public ResourceOverviewEntryButton(string hex)
    {
        RobustXamlLoader.Load(this);

        DepartmentIndicatorPanel.PanelOverride = new StyleBoxFlat(Color.FromHex(hex, Color.White));

        OverviewButton.OnPressed += _ => OnPressed?.Invoke();
    }
}
