using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Popups;

[GenerateTypedNameReferences]
public sealed partial class CreateLoadoutPopup : FancyWindow
{
    public event Action<LoadoutCreationRequest>? OnSubmit;

    public CreateLoadoutPopup(Dictionary<Guid, DenLoadoutCategory> categories, DenLoadout? maybeLoadout = null)
    {
        RobustXamlLoader.Load(this);

        var index = 0;

        if (maybeLoadout is { } existingLoadout)
        {
            var categoryId = existingLoadout.LoadoutCategory;
            var category = categories[categoryId];

            LoadoutNameEdit.Text = existingLoadout.Name;
            OptionsCategories.AddItem(category.Name, index);
            OptionsCategories.SetItemMetadata(index, categoryId);

            index += 1;
        }

        foreach (var (categoryId, category) in categories)
        {
            if (maybeLoadout is { } loadoutProfile
                && categoryId == loadoutProfile.LoadoutCategory)
                continue;

            OptionsCategories.AddItem(category.Name);
            OptionsCategories.SetItemMetadata(index, categoryId);

            index += 1;
        }

        OptionsCategories.OnItemSelected += args => OptionsCategories.SelectId(args.Id);
        ButtonSubmit.OnPressed += _ => OnSubmitPressed(maybeLoadout);
    }

    private void OnSubmitPressed(DenLoadout? maybeLoadout = null)
    {
        var categorySelectedIndex = OptionsCategories.SelectedId;
        var categorySelectedId = (Guid) (OptionsCategories.GetItemMetadata(categorySelectedIndex) ?? Guid.Empty);

        if (categorySelectedId == Guid.Empty)
            return;

        var request = new LoadoutCreationRequest
        {
            ExistingLoadoutId = maybeLoadout?.Id ?? null,
            LoadoutName = LoadoutNameEdit.Text,
            CategoryId = categorySelectedId,
        };

        OnSubmit?.Invoke(request);
    }
}

public record struct LoadoutCreationRequest
{
    public Guid? ExistingLoadoutId { get; set; }
    public string LoadoutName { get; set; }
    public Guid CategoryId { get; set; }
}
