using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Containers.UI;

[GenerateTypedNameReferences]
public sealed partial class ContainerSelectionEntityView : Control
{
    public ContainerSelectionEntityView()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Sets the displayed prototype.
    /// </summary>
    /// <param name="proto">The prototype to display.</param>
    public void SetEntityPrototype(EntProtoId proto)
    {
        EntityView.SetPrototype(proto);
    }
}
