using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Containers.UI;

[GenerateTypedNameReferences]
public sealed partial class ContainerSelectionWindow : FancyWindow
{
    public ContainerSelectionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetControls(IEnumerable<ContainerSelectionControl> controls)
    {
        // Remove any old controls to prevent duplicates.
        Options.RemoveAllChildren();
        foreach (var control in controls)
        {
            Options.AddChild(control);
        }
    }
}
