using Content.Shared.EntityTable;
using Content.Shared.EntityTable.EntitySelectors;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Containers.UI;

[GenerateTypedNameReferences]
public sealed partial class ContainerSelectionControl : Control
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public ContainerSelectionControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    ///     Set the display data used by this control.
    /// </summary>
    /// <param name="entMan">Entity manager (used for retrieving the list of spqwns from EntityTableSelectors)</param>
    /// <param name="selectionName">The localization string for the selection category.</param>
    /// <param name="tables">The map of containers to EntityTableSelectors for this selection, used to display the contained entities.</param>
    public void SetData(IEntityManager entMan, LocId selectionName, Dictionary<string, EntityTableSelector> tables)
    {
        HeaderLabel.Text = Loc.GetString(selectionName);

        foreach (var entContainer in tables)
        {
            var ctx = new EntityTableContext();
            foreach (var (proto, _) in entContainer.Value.ListSpawns(entMan, _prototypeManager, ctx))
            {
                var protoView = new ContainerSelectionEntityView();
                protoView.SetEntityPrototype(proto);

                EntityGrid.AddChild(protoView);
            }
        }
    }
}
