- type: antag
  id: MothershipCore
  name: roles-antag-mothership-core-name
  antagonist: true
  setPreference: true
  objective: roles-antag-mothership-core-objective
  # Begin DEN: Use PlayerRequirements
  # requirements:
  # - !type:RoleTimeRequirement
  #   role: JobBorg
  #   time: 18000  # 5 hrs
  playerRequirements:
  - !type:PlayerJobPlaytimeRequirement
    job: Borg
    minTime: 5h
  # End DEN
  guides: [ Xenoborgs ]

- type: antagSpecifier
  parent: RestrictedAntag
  id: MothershipCore
  prefRoles: [ MothershipCore ]
  spawnerPrototype: SpawnPointGhostRoleMothershipCore

- type: antag
  id: Xenoborg
  name: roles-antag-xenoborg-name
  antagonist: true
  setPreference: true
  objective: roles-antag-xenoborg-objective
  # Begin DEN: Use PlayerRequirements
  # requirements:
  # - !type:RoleTimeRequirement
  #   role: JobBorg
  #   time: 18000  # 5 hrs
  playerRequirements:
  - !type:PlayerJobPlaytimeRequirement
    job: Borg
    minTime: 5h
  # End DEN
  guides: [ Xenoborgs ]

- type: antagSpecifier
  abstract: true
  parent: RestrictedAntag
  id: BaseXenoborg
  prefRoles: [ Xenoborg ]
  spawnerPrototype: SpawnPointGhostRoleXenoborg

- type: antagSpecifier
  parent: BaseXenoborg
  id: Xenoborg
