using Content.Client._DEN.Denu.Core;
using Content.Client._DEN.Denu.UI.Denu;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using UiControl = Robust.Client.UserInterface.Control;

namespace Content.Client._DEN.Denu.Modules.Chat;

[GenerateTypedNameReferences]
public sealed partial class EarmuffsTab : UiControl
{
    private readonly DenuUIController _denuUIController;
    private EarmuffsDenuModule? _module;
    private bool _handlersSetup;
    private DenuUiBindings.BoundSlider? _rangeBinding;

    public EarmuffsTab()
    {
        RobustXamlLoader.Load(this);
        _denuUIController = UserInterfaceManager.GetUIController<DenuUIController>();
    }

    public EarmuffsTab(EarmuffsDenuModule module) : this()
    {
        SetModule(module);
    }

    public void SetModule(EarmuffsDenuModule module)
    {
        _module = module;
        SetupEventHandlers();
        RefreshFromSettings();
    }

    private void SetupEventHandlers()
    {
        if (_module == null || _handlersSetup)
            return;

        _rangeBinding = DenuUiBindings.BindSliderOnRelease(
            RangeSlider,
            RangeLabel,
            value => _denuUIController.SetEarmuffRange(value, sendUpdate: false),
            value => _denuUIController.SetEarmuffRange(value, sendUpdate: true),
            roundingDecimals: 2,
            labelFormat: "F1");

        _handlersSetup = true;
    }

    public void RefreshFromSettings()
    {
        if (_module == null)
            return;

        _rangeBinding?.Refresh(_module.EditRange);
    }
}
