using Content.Client._DEN.Denu.Core;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using UiControl = Robust.Client.UserInterface.Control;

namespace Content.Client._DEN.Denu.Modules.Chat;

[GenerateTypedNameReferences]
public sealed partial class FormatterTab : UiControl
{
    private const string PreviewText = "\"Hello! *italic* **bold** ***bolditalic***\" *looks at you*";

    private ChatFormatterDenuModule? _module;
    private bool _handlersSetup;
    private DenuUiBindings.BoundCheckBox? _autoFormatterBinding;
    private DenuUiBindings.BoundCheckBox? _removeAsterisksBinding;
    private DenuUiBindings.BoundColorSelector? _dialogueColorBinding;
    private DenuUiBindings.BoundColorSelector? _emoteColorBinding;

    public FormatterTab()
    {
        RobustXamlLoader.Load(this);
        PreviewRawLabel.SetMessage(BuildRawPreview());
    }

    public FormatterTab(ChatFormatterDenuModule module) : this()
    {
        SetModule(module);
    }

    public void SetModule(ChatFormatterDenuModule module)
    {
        _module = module;
        SetupEventHandlers();
        RefreshFromSettings();
    }

    private void SetupEventHandlers()
    {
        if (_module == null || _handlersSetup)
            return;

        _autoFormatterBinding = DenuUiBindings.BindCheckBox(AutoFormatterCheckBox, pressed =>
        {
            _module.SetEnabled(pressed);
            UpdatePreview();
        });

        _removeAsterisksBinding = DenuUiBindings.BindCheckBox(RemoveAsterisksCheckBox, pressed =>
        {
            _module.SetRemoveAsterisks(pressed);
            UpdatePreview();
        });

        DialogueColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        _dialogueColorBinding = DenuUiBindings.BindColorSelector(DialogueColorSelector, color =>
        {
            _module.SetDialogueColor(color);
            UpdatePreview();
        });

        EmoteColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        _emoteColorBinding = DenuUiBindings.BindColorSelector(EmoteColorSelector, color =>
        {
            _module.SetEmoteColor(color);
            UpdatePreview();
        });

        _handlersSetup = true;
    }

    public void RefreshFromSettings()
    {
        if (_module == null)
            return;

        _autoFormatterBinding?.Refresh(_module.Enabled);
        _removeAsterisksBinding?.Refresh(_module.RemoveAsterisks);
        _dialogueColorBinding?.Refresh(_module.GetDialogueColor());
        _emoteColorBinding?.Refresh(_module.GetEmoteColor());
        UpdatePreview();
    }

    private void UpdatePreview()
    {
        if (_module == null)
            return;

        string formatted = _module.FormatPreviewMessage(PreviewText);
        PreviewFormattedLabel.SetMessage(BuildFormattedPreview(formatted));
    }

    private static FormattedMessage BuildRawPreview()
    {
        FormattedMessage msg = new FormattedMessage();
        msg.AddText(PreviewText);
        return msg;
    }

    private static FormattedMessage BuildFormattedPreview(string markup)
    {
        if (FormattedMessage.TryFromMarkup(markup, out FormattedMessage? msg))
            return msg!;

        FormattedMessage fallback = new FormattedMessage();
        fallback.AddText(markup);
        return fallback;
    }
}
