using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Holosign.UI;

[GenerateTypedNameReferences]
public sealed partial class LabelableHolosignProjectorWindow : DefaultWindow
{
    public event Action<string, bool>? OnDescriptionChanged;

    private string _description = string.Empty;

    public LabelableHolosignProjectorWindow()
    {
        RobustXamlLoader.Load(this);

        DescriptionTextEdit.OnTextChanged += e =>
        {
            var text = Rope.Collapse(e.TextRope).Trim();
            _description = text;
            OnDescriptionChanged?.Invoke(_description, IsNSFW.Pressed);
        };

        IsNSFW.OnPressed += e =>
        {
            var text = Rope.Collapse(DescriptionTextEdit.TextRope).Trim();
            _description = text;
            OnDescriptionChanged?.Invoke(_description, IsNSFW.Pressed);
        };
    }

    public void SetCurrentDescription(string description)
    {
        if (description == _description)
            return;

        _description = description;
        if (!DescriptionTextEdit.HasKeyboardFocus())
        {
            var rope = new Rope.Leaf(description);
            DescriptionTextEdit.TextRope = rope;
        }
    }

    public void SetCurrentNsfw(bool isNsfw)
    {
        IsNSFW.Pressed = isNsfw;
    }
}
