using Content.Shared._DEN.Recolor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Recolor.UI;

[GenerateTypedNameReferences]
public sealed partial class RecolorApplierColorSelectorMenu : DefaultWindow
{
    public Action<Color>? OnColorChanged;

    public RecolorApplierColorSelectorMenu()
    {
        RobustXamlLoader.Load(this);

        ColorSelector.OnColorChanged += color =>
        {
            OnColorChanged?.Invoke(color);
        };
    }

    // Set the color selector's color.
    public void SelectColor(Color color)
    {
        ColorSelector.Color = color;
    }
}
