- type: entity
  name: everyspice pods
  parent: FoodProduceBase
  id: FoodEveryspice
  description: The long, pale pods of the everyspice plant. A flavorful addition to food when ground.
  components:
  - type: FlavorProfile
    flavors:
    - spices
  - type: Solution # DEN - Update for solutions refactor
    solution:
      reagents:
      - ReagentId: Everyspice
        Quantity: 5
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/everyspice.rsi
    state: produce
  - type: Tag
    tags:
    - Fruit
  - type: AtmosExposed
  - type: Temperature
    heatCapacity: 15000 # DEN: fix test fail
  - type: Construction
    graph: Everyspice
    node: start
    defaultTarget: FoodEveryspiceRoasted

- type: entity
  name: roasted everyspice pods
  parent: FoodProduceBase
  id: FoodEveryspiceRoasted
  description: Aromatic, charred pods of the everyspice plant. A piquant addition to food when ground.
  components:
  - type: FlavorProfile
    flavors:
    - peppery
  - type: Solution # DEN - Update for solutions refactor
    solution:
      reagents:
      - ReagentId: Blackpepper
        Quantity: 5
  - type: Sprite
    sprite: _NF/Objects/Specific/Hydroponics/everyspice.rsi
    state: produce-roasted
  - type: Tag
    tags:
    - Fruit
  - type: Construction
    graph: Everyspice
    node: FoodEveryspiceRoasted
