// SPDX-FileCopyrightText: 2025 Cam
// SPDX-FileCopyrightText: 2025 Cami
// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._DEN.Denu.Core;
using Content.Client._DEN.Denu.UI.Denu.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using UiControl = Robust.Client.UserInterface.Control;

namespace Content.Client._DEN.Denu.UI.Denu;

[GenerateTypedNameReferences]
public sealed partial class DenuWindow : AnimatedWindow
{
    private readonly DenuUIController _denuUIController;
    private readonly IPlayerManager _playerManager;

    private readonly List<UiControl> _tabContents = new();

    public DenuWindow()
    {
        RobustXamlLoader.Load(this);
        _denuUIController = UserInterfaceManager.GetUIController<DenuUIController>();
        _playerManager = IoCManager.Resolve<IPlayerManager>();
        InitializeUI();
    }

    private void InitializeUI()
    {
        SetupWindow();
        SetupModuleTabs();
    }

    private void SetupWindow()
    {
        SetupPaneStyles();
        Title = "Denu";

        DenuModuleContext? context = _denuUIController.ModuleRegistry.Context;
        if (context != null)
        {
            ScopeSelector.SetScope(context.IsEditingGlobal);
            ScopeSelector.OnScopeChanged += global => context.SetScope(global);
            context.OnEditStateChanged += OnContextScopeChanged;
        }

        if (_playerManager.LocalSession?.AttachedEntity is { } playerEntity)
        {
            ScopeSelector.SetEntity(playerEntity);
        }
    }

    private void SetupPaneStyles()
    {
        WindowBodyPanel.PanelOverride = CreatePane(Color.FromHex("#20212B"), Color.FromHex("#4A4D62"), new Thickness(1));
        SidebarPanel.PanelOverride = CreatePane(Color.FromHex("#181923"), Color.FromHex("#3D4054"), new Thickness(0, 0, 1, 0));
        ScopePanel.PanelOverride = CreatePane(Color.FromHex("#252735"), Color.FromHex("#3D4054"), new Thickness(0, 0, 0, 1));
        ContentPanel.PanelOverride = CreatePane(Color.FromHex("#20212B"), Color.Transparent, new Thickness(0));
    }

    private static StyleBoxFlat CreatePane(Color background, Color border, Thickness borderThickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = borderThickness
        };
    }

    private void OnContextScopeChanged()
    {
        DenuModuleContext? context = _denuUIController.ModuleRegistry.Context;
        if (context != null)
        {
            ScopeSelector.SetScope(context.IsEditingGlobal);
        }
    }

    private void SetupModuleTabs()
    {
        DenuModuleRegistry registry = _denuUIController.ModuleRegistry;

        Sidebar.ClearTabs();
        _tabContents.Clear();

        int index = 0;

        foreach (IDenuModule module in registry.Modules)
        {
            UiControl tabContent = module.CreateTabContent();

            ScrollContainer scrollContainer = new ScrollContainer
            {
                VerticalExpand = true,
                HorizontalExpand = true,
                HScrollEnabled = false
            };

            scrollContainer.AddChild(tabContent);

            _tabContents.Add(scrollContainer);
            Sidebar.AddTab(module.DisplayName, index++);
        }

        _tabContents.Add(CreateHelpTab());
        Sidebar.AddTab("Help", index++);

        Sidebar.OnTabSelected += OnSidebarTabSelected;

        if (_tabContents.Count > 0)
        {
            OnSidebarTabSelected(0);
        }
    }

    private void OnSidebarTabSelected(int index)
    {
        ContentArea.RemoveAllChildren();
        if (index >= 0 && index < _tabContents.Count)
        {
            ContentArea.AddChild(_tabContents[index]);
        }
    }

    private UiControl CreateHelpTab()
    {
        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HScrollEnabled = false
        };
        var helpDisplay = new FormattedTextDisplay { StyleClasses = { "AngleRect" }, FilePath = "/ServerInfo/DenuHelp.txt" };
        scroll.AddChild(helpDisplay);

        helpDisplay.Formatter = text => _denuUIController.FormatMessage(text);

        return scroll;
    }

    public override void Close()
    {
        _denuUIController.IsOpen = false;
        base.Close();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _denuUIController.IsOpen = false;

            DenuModuleContext? context = _denuUIController.ModuleRegistry.Context;
            if (context != null)
            {
                context.OnEditStateChanged -= OnContextScopeChanged;
            }
        }
        base.Dispose(disposing);
    }
}
