using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;

[GenerateTypedNameReferences]
public sealed partial class DenCategoryContainer : PanelContainer
{
    public event Action<DenLoadout, DenLoadoutAction>? OnClickLoadoutAction;
    public readonly Dictionary<Guid, DenLoadoutContainer> LoadoutContainers = new();
    public List<DenLoadout> Loadouts;
    private bool _isExpanded;

    private DenLoadoutCategory _category;

    public DenCategoryContainer(DenLoadoutCategory category,
        List<DenLoadout> loadouts)
    {
        RobustXamlLoader.Load(this);

        Loadouts = loadouts;
        _category = category;

        RefreshCategoryName(category);
        RefreshCategoryColor(category);
        RefreshLoadoutContainers(loadouts);

        HeaderButton.OnPressed += _ => ToggleExpanded();
        UpdateExpandedState();
    }

    public void UpdateCategory(DenLoadoutCategory category, List<DenLoadout> loadouts)
    {
        RefreshCategoryName(category);
        RefreshCategoryColor(category);
        RefreshLoadoutContainers(loadouts);

        Loadouts = loadouts;
        _category = category;
    }

    private void RefreshCategoryName(DenLoadoutCategory category)
    {
        CategoryNameLabel.Text = category.Name;
    }

    private void RefreshCategoryColor(DenLoadoutCategory category)
    {
        var color = Color.TryFromHex(category.Color);

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = color ?? Color.White
        };
    }

    private void RefreshLoadoutContainers(List<DenLoadout> loadoutProfiles)
    {
        foreach (var loadoutProfile in loadoutProfiles)
        {
            DenLoadoutContainer container;

            if (LoadoutContainers.TryGetValue(loadoutProfile.Id, out var cachedContainer))
            {
                container = cachedContainer;
            }
            else
            {
                container = new DenLoadoutContainer(loadoutProfile);
                container.Visible = true;
                container.OnClickLoadoutAction += DoLoadoutAction;

                LoadoutContainers.Add(loadoutProfile.Id, container);
                LoadoutContainer.AddChild(container);
            }

            container.UpdateLoadout(loadoutProfile);
        }

        var countText = $"{LoadoutContainers.Count} loadout";

        if (LoadoutContainers.Count != 1)
            countText += "s";

        CategoryLoadoutCount.Text = countText;
    }

    private void DoLoadoutAction(DenLoadout profile, DenLoadoutAction action)
    {
        OnClickLoadoutAction?.Invoke(profile, action);
    }

    public void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        ContentPanel.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }
}
