using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;

[GenerateTypedNameReferences]
public sealed partial class DenCategoryActions : ContainerButton
{
    public event Action? OnTryCategoryEdit;
    public event Action? OnTryCategoryDelete;

    public DenCategoryActions()
    {
        RobustXamlLoader.Load(this);

        ButtonEdit.OnPressed += _ => OnTryCategoryEdit?.Invoke();
        ButtonDelete.OnPressed += _ => OnTryCategoryDelete?.Invoke();
    }

    public void SetDeleteDisabled(bool deleteDisabled)
    {
        ButtonDelete.Disabled = deleteDisabled;
    }
}
