using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;

[GenerateTypedNameReferences]
public sealed partial class DenCategoryContainer : PanelContainer
{
    public event Action<DenLoadoutProfile, DenLoadoutAction>? OnClickLoadoutAction;
    public readonly Dictionary<Guid, DenLoadoutContainer> LoadoutContainers = new();
    public List<DenLoadoutProfile> Loadouts;
    private bool _isExpanded;

    private LoadoutProfileCategory _profileCategory;

    public DenCategoryContainer(LoadoutProfileCategory profileCategory,
        List<DenLoadoutProfile> loadouts)
    {
        RobustXamlLoader.Load(this);

        Loadouts = loadouts;
        _profileCategory = profileCategory;

        RefreshCategoryName(profileCategory);
        RefreshCategoryColor(profileCategory);
        RefreshLoadoutContainers(loadouts);

        HeaderButton.OnPressed += _ => ToggleExpanded();
        UpdateExpandedState();
    }

    public void UpdateCategory(LoadoutProfileCategory profileCategory, List<DenLoadoutProfile> loadouts)
    {
        RefreshCategoryName(profileCategory);
        RefreshCategoryColor(profileCategory);
        RefreshLoadoutContainers(loadouts);

        Loadouts = loadouts;
        _profileCategory = profileCategory;
    }

    private void RefreshCategoryName(LoadoutProfileCategory profileCategory)
    {
        CategoryNameLabel.Text = profileCategory.Name;
    }

    private void RefreshCategoryColor(LoadoutProfileCategory profileCategory)
    {
        var color = Color.TryFromHex(profileCategory.Color);

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = color ?? Color.White
        };
    }

    private void RefreshLoadoutContainers(List<DenLoadoutProfile> loadoutProfiles)
    {
        foreach (var loadoutProfile in loadoutProfiles)
        {
            DenLoadoutContainer container;

            if (LoadoutContainers.TryGetValue(loadoutProfile.Id, out var cachedContainer))
            {
                container = cachedContainer;
            }
            else
            {
                container = new DenLoadoutContainer(loadoutProfile);
                container.Visible = true;
                container.OnClickLoadoutAction += DoLoadoutAction;

                LoadoutContainers.Add(loadoutProfile.Id, container);
                LoadoutContainer.AddChild(container);
            }

            container.UpdateLoadout(loadoutProfile);
        }

        var countText = $"{LoadoutContainers.Count} loadout";

        if (LoadoutContainers.Count != 1)
            countText += "s";

        CategoryLoadoutCount.Text = countText;
    }

    private void DoLoadoutAction(DenLoadoutProfile profile, DenLoadoutAction action)
    {
        OnClickLoadoutAction?.Invoke(profile, action);
    }

    public void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        ContentPanel.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }
}
