using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;

[GenerateTypedNameReferences]
public sealed partial class DenLoadoutContainer : ContainerButton
{
    public event Action<DenLoadout, DenLoadoutAction>? OnClickLoadoutAction;

    private DenLoadout _loadout;

    public DenLoadoutContainer(DenLoadout loadoutProfile)
    {
        RobustXamlLoader.Load(this);

        _loadout = loadoutProfile;

        LoadoutNameLabel.Text = loadoutProfile.Name;

        ButtonEditJobs.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadout, DenLoadoutAction.EditJobs);
        ButtonEditLoadouts.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadout, DenLoadoutAction.EditLoadouts);
        ButtonEditLoadoutProfile.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadout, DenLoadoutAction.EditLoadoutProfile);
        ButtonDeleteProfile.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadout, DenLoadoutAction.DeleteLoadoutProfile);
    }

    public void UpdateLoadout(DenLoadout loadout)
    {
        if (_loadout == loadout)
            return;

        if (loadout.Name != _loadout.Name)
            LoadoutNameLabel.Text = loadout.Name;

        _loadout = loadout;
    }
}

public enum DenLoadoutAction
{
    EditJobs,
    EditLoadouts,
    EditLoadoutProfile,
    DeleteLoadoutProfile
}
