using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;

[GenerateTypedNameReferences]
public sealed partial class DenLoadoutContainer : ContainerButton
{
    public event Action<DenLoadoutProfile, DenLoadoutAction>? OnClickLoadoutAction;

    private DenLoadoutProfile _loadoutProfile;

    public DenLoadoutContainer(DenLoadoutProfile loadoutProfileProfile)
    {
        RobustXamlLoader.Load(this);

        _loadoutProfile = loadoutProfileProfile;

        LoadoutNameLabel.Text = loadoutProfileProfile.Name;

        ButtonEditJobs.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadoutProfile, DenLoadoutAction.EditJobs);
        ButtonEditLoadouts.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadoutProfile, DenLoadoutAction.EditLoadouts);
        ButtonEditLoadoutProfile.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadoutProfile, DenLoadoutAction.EditLoadoutProfile);
        ButtonDeleteProfile.OnPressed += _ =>
            OnClickLoadoutAction?.Invoke(_loadoutProfile, DenLoadoutAction.DeleteLoadoutProfile);
    }

    public void UpdateLoadout(DenLoadoutProfile loadoutProfile)
    {
        if (_loadoutProfile == loadoutProfile)
            return;

        if (loadoutProfile.Name != _loadoutProfile.Name)
            LoadoutNameLabel.Text = loadoutProfile.Name;

        _loadoutProfile = loadoutProfile;
    }
}

public enum DenLoadoutAction
{
    EditJobs,
    EditLoadouts,
    EditLoadoutProfile,
    DeleteLoadoutProfile
}
