using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;

[GenerateTypedNameReferences]
public sealed partial class LoadoutItemSelection : PanelContainer
{
    public LoadoutItemSelection()
    {
        RobustXamlLoader.Load(this);
    }
}

