using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class CreateCategoryPopup : FancyWindow
{
    public event Action<CategoryCreationRequest>? OnSubmit;

    public CreateCategoryPopup(DenLoadoutCategory? maybeCategory)
    {
        RobustXamlLoader.Load(this);

        if (maybeCategory is { } existingCategory)
        {
            var color = Color.TryFromHex(existingCategory.Color) ?? Color.White;

            CategoryNameEdit.Text = existingCategory.Name;
            CategoryColorPicker.Color = color;
        }

        ButtonSubmit.OnPressed += _ => OnSubmitPressed(maybeCategory);
    }

    private void OnSubmitPressed(DenLoadoutCategory? existingCategory)
    {
        var request = new CategoryCreationRequest
        {
            ExistingCategoryId = existingCategory?.Id ?? null,
            CategoryName = CategoryNameEdit.Text,
            CategoryColor = CategoryColorPicker.Color
        };

        OnSubmit?.Invoke(request);
    }
}

public record struct CategoryCreationRequest
{
    public Guid? ExistingCategoryId { get; set; }
    public string CategoryName { get; set; }
    public Color CategoryColor { get; set; }
}
