using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class CreateLoadoutPopup : FancyWindow
{
    public event Action<LoadoutCreationRequest>? OnSubmit;

    private List<(Guid CategoryId, string CategoryName)> _categories;

    public CreateLoadoutPopup(List<(Guid CategoryId, string CategoryName)> categories)
    {
        RobustXamlLoader.Load(this);

        _categories = categories;

        var index = 0;

        foreach (var category in categories)
        {
            OptionsCategories.AddItem(category.CategoryName, index);
            index += 1;
        }

        OptionsCategories.OnItemSelected += args => OptionsCategories.SelectId(args.Id);
        ButtonSubmit.OnPressed += _ => OnSubmitPressed();
    }

    private void OnSubmitPressed()
    {
        var categorySelected = OptionsCategories.SelectedId;

        if (categorySelected >= _categories.Count)
            return;

        var category = _categories[categorySelected];
        var request = new LoadoutCreationRequest
        {
            LoadoutName = LoadoutNameEdit.Text,
            CategoryId = category.CategoryId
        };

        OnSubmit?.Invoke(request);
    }
}

public record struct LoadoutCreationRequest
{
    public string LoadoutName { get; set; }
    public Guid CategoryId { get; set; }
}
