using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class DenCategoryContainer : PanelContainer
{
    private DenLoadoutCategory _categoryDefinition;
    private List<DenLoadoutContainer> _loadouts = new();
    private bool _isExpanded;

    public DenCategoryContainer(DenLoadoutCategory category,
        List<DenLoadout> loadouts)
    {
        RobustXamlLoader.Load(this);

        _categoryDefinition = category;

        RefreshCategoryColor();
        RefreshLoadoutContainers(loadouts);

        HeaderButton.OnPressed += _ => ToggleExpanded();
        UpdateExpandedState();
    }

    private void RefreshCategoryColor()
    {
        var color = Color.TryFromHex(_categoryDefinition.Color);

        AccentBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = color ?? Color.White
        };
    }

    private void RefreshLoadoutContainers(List<DenLoadout> loadoutProfiles)
    {
        foreach (var loadoutProfile in loadoutProfiles)
        {
            var container = new DenLoadoutContainer(loadoutProfile);

            AddChild(container);
            _loadouts.Add(container);
        }
    }

    private void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        LoadoutContainer.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }
}
