using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class DenCategoryActions : ContainerButton
{
    public event Action? OnTryProfileEdit;
    public event Action? OnTryProfileDelete;

    public DenCategoryActions()
    {
        RobustXamlLoader.Load(this);

        ButtonEdit.OnPressed += _ => OnTryProfileEdit?.Invoke();
        ButtonDelete.OnPressed += _ => OnTryProfileDelete?.Invoke();
    }
}
