using Content.Shared._DEN.Loadout;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class DenLoadoutTab : ContainerButton
{
    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private CreateCategoryPopup? _createCategoryPopup;
    private CreateLoadoutPopup? _createLoadoutPopup;
    private HumanoidCharacterProfile? _profile;

    private readonly List<(Guid CategoryId, string CategoryName)> _popupCategories;
    private readonly List<DenCategoryContainer> _categories = [];

    public DenLoadoutTab()
    {
        RobustXamlLoader.Load(this);

        _popupCategories = new List<(Guid CategoryId, string CategoryName)>();
        ButtonCreateCategory.OnPressed += _ => OnTryCreateCategory();
        ButtonCreateLoadout.OnPressed += _ => OnTryCreateLoadout();
    }

    public void RefreshCategories()
    {
        _popupCategories.Clear();

        if (_profile?.LoadoutCategories == null)
            return;

        var canCreateLoadout = _profile.LoadoutCategories.Count == 0;
        ButtonCreateLoadout.Disabled = canCreateLoadout;
        ButtonCreateLoadout.ToolTip = !canCreateLoadout ? "You need at least one category." : null;
        ButtonCreateLoadout.TooltipDelay = 0.5f;

        foreach (var categoryContainer in _categories)
        {
            categoryContainer.Orphan();
        }

        _categories.Clear();

        foreach (var (categoryId, category) in _profile.LoadoutCategories)
        {
            _popupCategories.Add((categoryId, category.Name));

            var profiles = new List<DenLoadout>();

            foreach (var loadoutId in category.Members)
            {
                if (!_profile.LoadoutProfiles.TryGetValue(loadoutId, out var loadout))
                    continue;

                profiles.Add(loadout);
            }

            var categoryContainer = new DenCategoryContainer(category, profiles);
            categoryContainer.CategoryActions.OnTryProfileEdit += () => TryProfileEdit(category);
            categoryContainer.CategoryActions.OnTryProfileDelete += () => TryProfileDelete(category);

            _categories.Add(categoryContainer);
            LoadoutContainer.AddChild(categoryContainer);
        }
    }

    private void TryProfileEdit(DenLoadoutCategory category)
    {
        OnTryCreateCategory(category);
    }

    private void TryProfileDelete(DenLoadoutCategory category)
    {
        throw new NotImplementedException();
    }

    public void SetProfile(HumanoidCharacterProfile? newProfile)
    {
        _profile = newProfile;
        RefreshCategories();
    }

    private void OnTryCreateCategory(DenLoadoutCategory? existingCategory = null)
    {
        if (_createCategoryPopup != null)
            return;

        _createCategoryPopup = new CreateCategoryPopup(existingCategory);
        _createCategoryPopup.OnSubmit += OnSubmitNewCategory;
        _createCategoryPopup.OnClose += OnCloseCategoryPopup;
        _createCategoryPopup.OpenCentered();
    }

    private void OnSubmitNewCategory(CategoryCreationRequest request)
    {
        if (string.IsNullOrEmpty(request.CategoryName))
            return;

        var guid = request.ExistingCategoryId ?? Guid.NewGuid();
        var priority = GetNextCategoryPriority();
        var members = new HashSet<Guid>();

        if (_profile?.LoadoutCategories.TryGetValue(guid, out var loadout) == true)
        {
            priority = loadout.Priority;
            members.UnionWith(loadout.Members);
        }

        var category = new DenLoadoutCategory
        {
            Id = guid,
            Color = request.CategoryColor.ToHex(),
            Name = request.CategoryName,
            Priority = priority,
            Members = members
        };

        _profile = _profile?.WithLoadoutCategory(guid, category);
        OnPreferenceUpdated?.Invoke(_profile);

        RefreshCategories();
        OnCloseCategoryPopup();
    }

    private void OnTryCreateLoadout()
    {
        if (_createLoadoutPopup != null)
            return;

        _createLoadoutPopup = new CreateLoadoutPopup(_popupCategories);
        _createLoadoutPopup.OnSubmit += OnSubmitNewLoadout;
        _createLoadoutPopup.OnClose += OnCloseLoadoutPopup;
        _createLoadoutPopup.OpenCentered();
    }

    private void OnSubmitNewLoadout(LoadoutCreationRequest request)
    {
        if (string.IsNullOrEmpty(request.LoadoutName))
            return;

        var guid = Guid.NewGuid();
        var loadout = new DenLoadout
        {
            Id = guid,
            Name = request.LoadoutName,
            LoadoutCategory = request.CategoryId,
            Priority = GetNextLoadoutPriority(request.CategoryId),
            Loadouts = new HashSet<ProtoId<EntityLoadoutPrototype>>()
        };

        _profile = _profile?.WithNewLoadout(guid, request.CategoryId, loadout);
        OnPreferenceUpdated?.Invoke(_profile);

        RefreshCategories();
        OnCloseLoadoutPopup();
    }

    private int GetNextCategoryPriority()
    {
        if (_profile == null)
            return 0;

        var loadoutCategoryCount = _profile.LoadoutCategories.Count;
        return loadoutCategoryCount + 1;
    }

    private int GetNextLoadoutPriority(Guid categoryId)
    {
        var maybeCategory = _profile?.LoadoutCategories.Values
            .FirstOrNull(c => c.Id == categoryId);

        if (maybeCategory is not { } category)
            return 0;

        var memberCount = category.Members.Count;
        return memberCount + 1;
    }

    private void OnCloseCategoryPopup()
    {
        _createCategoryPopup?.Orphan();
        _createCategoryPopup = null;
    }

    private void OnCloseLoadoutPopup()
    {
        _createLoadoutPopup?.Orphan();
        _createLoadoutPopup = null;
    }
}
