using Content.Shared._DEN.Loadout;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class DenLoadoutContainer : ContainerButton
{
    private DenLoadout _loadout;

    public DenLoadoutContainer(DenLoadout loadoutProfile)
    {
        RobustXamlLoader.Load(this);

        _loadout = loadoutProfile;

        LoadoutNameLabel.Text = loadoutProfile.Name;

    }
}
