using System.Linq;
using Content.Client._DEN.Lobby.UI.Loadouts.Subcontainers;
using Content.Shared._DEN.Loadout;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutProfilesContainer : BoxContainer
{
    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private Popups.CreateCategoryPopup? _createCategoryPopup;
    private Popups.CreateLoadoutPopup? _createLoadoutPopup;
    private HumanoidCharacterProfile? _profile;

    private Dictionary<Guid, DenLoadoutCategory> _popupCategories;
    private Dictionary<Guid, DenCategoryContainer> _categories = [];

    public LoadoutProfilesContainer()
    {
        RobustXamlLoader.Load(this);

        _popupCategories = new Dictionary<Guid, DenLoadoutCategory>();
        ButtonCreateCategory.OnPressed += _ => OnTryCreateCategory();
        ButtonCreateLoadout.OnPressed += _ => OnTryCreateLoadout();
    }

    public void RefreshCategories()
    {
        _popupCategories.Clear();

        if (_profile?.LoadoutCategories == null)
            return;

        var canCreateLoadout = _profile.LoadoutCategories.Count == 0;
        ButtonCreateLoadout.Disabled = canCreateLoadout;

        foreach (var (categoryId, categoryContainer) in _categories)
        {
            if (!_profile.LoadoutCategories.ContainsKey(categoryId))
                categoryContainer.Orphan();
        }

        var newCategories = new Dictionary<Guid, DenCategoryContainer>();

        foreach (var (categoryId, category) in _profile.LoadoutCategories)
        {
            var categoryContainer = CreateCategory(categoryId);

            if (categoryContainer == null)
                continue;

            var orphanList = categoryContainer.LoadoutContainers
                .Where(c => !category.Members.Contains(c.Key))
                .ToList();

            foreach (var orphan in orphanList)
            {
                categoryContainer.LoadoutContainers.Remove(orphan.Key);
                orphan.Value.Orphan();
            }

            if (orphanList.Count > 0)
                categoryContainer.UpdateCategory(category, categoryContainer.Loadouts);

            newCategories.Add(categoryId, categoryContainer);
        }

        _categories = newCategories;
    }

    private DenCategoryContainer? CreateCategory(Guid categoryId)
    {
        if (_profile == null
            || !_profile.LoadoutCategories.TryGetValue(categoryId, out var category))
            return null;

        _popupCategories = new Dictionary<Guid, DenLoadoutCategory>(_profile.LoadoutCategories);

        var profiles = new List<DenLoadout>();

        foreach (var loadoutId in category.Members)
        {
            if (!_profile.LoadoutProfiles.TryGetValue(loadoutId, out var loadout))
                continue;

            profiles.Add(loadout);
        }

        DenCategoryContainer categoryContainer;

        if (_categories.TryGetValue(category.Id, out var cachedContainer))
        {
            categoryContainer = cachedContainer;
            categoryContainer.UpdateCategory(category, profiles);
        }
        else
        {
            categoryContainer = new DenCategoryContainer(category, profiles);
            categoryContainer.CategoryActions.OnTryCategoryEdit += () => TryCategoryEdit(category);
            categoryContainer.CategoryActions.OnTryCategoryDelete += () => TryCategoryDelete(category);
            categoryContainer.OnClickLoadoutAction += OnClickLoadoutAction;

            LoadoutContainer.AddChild(categoryContainer);
            _categories.Add(category.Id, categoryContainer);
        }

        categoryContainer.CategoryActions.SetDeleteDisabled(profiles.Count > 0);
        return categoryContainer;
    }

    private void OnClickLoadoutAction(DenLoadout loadout, DenLoadoutAction loadoutAction)
    {
        switch (loadoutAction)
        {
            case DenLoadoutAction.EditJobs:
                OnClickEditJobLoadouts(loadout);
                break;
            case DenLoadoutAction.EditLoadouts:
                OnClickEditLoadouts(loadout);
                break;
            case DenLoadoutAction.EditLoadoutProfile:
                OnClickEditLoadoutProfile(loadout);
                break;
            case DenLoadoutAction.DeleteLoadoutProfile:
                OnClickDeleteLoadoutProfile(loadout);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(loadoutAction), loadoutAction, null);
        }
    }

    private void TryCategoryEdit(DenLoadoutCategory category)
    {
        OnTryCreateCategory(category);
    }

    private void TryCategoryDelete(DenLoadoutCategory category)
    {
        if (_profile == null
            || !_profile.LoadoutCategories.ContainsKey(category.Id))
            return;

        _profile = _profile.WithoutLoadoutCategory(category);
        SetDirty(_profile);
        RefreshCategories();
    }

    private void SetDirty(HumanoidCharacterProfile? profile)
    {
        OnPreferenceUpdated?.Invoke(profile);
    }

    public void SetProfile(HumanoidCharacterProfile? newProfile)
    {
        _profile = newProfile;
    }
}
