- type: job
  id: Mantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobMantis
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 20h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 8h
  startingGear: MantisGear
  icon: "JobIconMantis"
  supervisors: job-supervisors-rd # change to job-supervisors-Epi when Mystagogue is added if we go that path
  access:
  - Mantis
  - Research
  - Maintenance

- type: startingGear
  id: MantisGear
  equipment:
    id: MantisPDA
    ears: ClothingHeadsetMantis
#  storage:
#    back:
#    - Stuff

- type: chameleonOutfit
  id: MantisChameleonOutfit
  job: Mantis
  equipment:
    head: ClothingHeadHoodMantisDark
    eyes: ClothingEyesGlassesEpistemicsMantisMirrored
    mask: ClothingMaskMantisRitual
    neck: ClothingNeckCloakMantisDark
    jumpsuit: ClothingUniformJumpsuitMantisDark
    outerClothing: ClothingOuterWinterCoatMantisDarkFolded
    gloves: ClothingHandsGlovesMantisDark
    shoes: ClothingShoesSandalsMantisDark
    back: ClothingBackpackMantis
